### ISSUE TITLE
Make the module available for install within Foundry

### ISSUE THREAD

**Issue by orffen** [DC23/basicfantasyrpg-corerules-en#1]
Hey Stew,

Would love to see the module made available for install within Foundry - you can submit it here: https://foundryvtt.com/packages/submit

**Comment by Stew-rt** [comment]
I'd like to do this once I've at least got a first draft of the monsters done.. Or I feel i could cause much confusion to users.

**Comment by Stew-rt** [comment]
Thanks to totallybanjaxed, we got to a releasable stage. I've submitted the module to foundry for approval.

**Comment by Stew-rt** [comment]
It's published.. https://foundryvtt.com/packages/basicfantasyrpg-corerules-en
