### ISSUE TITLE
Missing ammunition

### ISSUE THREAD

**Issue by horusofoz** [DC23/basicfantasyrpg-corerules-en#13]
Missing equipment entries for all ammunition types.

- Shortbow Arrow
- Silver Shortbow Arrow
- Longbow Arrow
- Silver Longbow Arrow
- Light Quarrel
- Silver Light Quarrel
- Heavy Quarrel
- Silver Heavy Quarrel
- Bullet
- Stone

See page 11 from core rules.

**Comment by Stew-rt** [comment]
Thanks for the heads up - i'll get them added over this week.

**Comment by Stew-rt** [comment]
Added in 0.1.2 as Equipment.
