### ISSUE TITLE
Foundry 11

### ISSUE THREAD

**Issue by Stew-rt** [DC23/basicfantasyrpg-corerules-en#15]
The Package still loads successfully.

Warnings:
The module "basicfantasyrpg-corerules-en" contains dependencies using "name" which is deprecated in favor of "id"
The module "basicfantasyrpg-corerules-en" contains "dependencies" which is deprecated in favor of "relationships.requires"

New features:
Looks like compendium folders are now native, I'll consider putting resources into a folder structure to reduce the amount of compendiums I have to include.

**Comment by revwez** [comment]
Is there any update on a v11 compatible version?

**Comment by DC23** [comment]
@revwez I'm taking over maintenance on this module. While I can't give dates yet, I'm starting to look at a two-step plan:

1. An update to Foundry v12 with the existing BFRPG 3rd edition content
2. Then the slower work of updating to BFRPG 4th edition content, using a more automated data processing pipeline.

So, even though I'll be closing this issue, work is underway once more.
