### ISSUE TITLE
Foundry v12+

### ISSUE THREAD

**Issue by DC23** [DC23/basicfantasyrpg-corerules-en#17]
Not so much an issue as a discussion :)

I've been working with Orffen on bringing the BFRPG system up to Foundry v12 (successfully, as you can see from merged PRs), and I'm now turning my attention to this module. 

I'm working with Solomoriah and hopefully others on a [BFRPG Bestiary Data Project](https://github.com/Solomoriah/BFRPG-Bestiary) that is producing 4th edition reference data in code-consumable JSON format. Once Solo completes the bestiary, I plan to extend that with armor, weapons, spells etc. The goal there is to build up to date BFRPG reference data that can fuel multiple down-stream projects like this one. Rather than reinvent the effort to transcribe information from the books, that project will do a lot of the work once for others to share. I'll write some in-Foundry importer macros that use the BFRPG classes to create items from the reference data that we can edit by hand. That's only part of the challenge.

Another part, as I'm sure you know, is that Foundry changed their compendium database formats completely, which requires an entirely new build workflow in the module. It's not unworkable, just different. I've got the approach in hand - I need it for the Easy Timekeeping module since I'm adding a compendium of macros to that, but it means this module needs a complete overhaul - all content updated to 4th edition, data structure migration, and new workflows (node CLI steps on the build machine where Foundry testing and data entry is done pre commit to Git to convert to JSON format database files & a GitHub action in the release build that converts back to binary files for inclusion in the build artifact).

An advantage you've already identified is that the new compendium format supports nested folders, so the structure can be simplified.

I can take on all of this in a fork, but that's only going to work if you're still here at this end to merge the PRs, work with me a little and submit new releases to Foundry. That's why I'm submitting this GitHub Issue: to check in. If you've had enough, then that's ok too but I need to know. The alternative in that case is for us to integrate the core rules content into the BFRPG system.

**Comment by Stew-rt** [comment]
Hi DC23 - to be honest, I'd be willing to hand over ownership of this repo (and the foundry Add-On, if that's possible).
I've found i've not had the time to maintain this properly.

**Comment by DC23** [comment]
Thanks. Bringing me onto this module directly would help with continuity of the module identity, but you're right. If you want to step back from this project then the Foundry release side is the problem, not GitHub. One of the Foundry admins might be able to transfer ownership of the module in their system, but equally they might require me to submit a new module (with a module ID change). You'll have to ask them. If they can transfer ownership then I'm happy to take over as custodian.

On the GitHub side, if you are ok with transferring ownership of this repo, then that's the best way to preserve the history and let the work continue.

Transferring the repo would make sense even if Foundry can't transfer the Foundry module. In that case, I'll have to change the module ID, update the name slightly, update the module page, Readme, BFRPG system links, etc explaining why and then we continue from there.

**Comment by Stew-rt** [comment]
I've started the GitHub repo transfer to you.
What is the account name/email for your Foundry account? I'll likely need that for the Foundry Add On transfer (if possible)

EDIT: I've just sent an email for the Foundry support team to ask what the process is.

**Comment by DC23** [comment]
On Foundry I'm [jugglindan](https://foundryvtt.com/community/jugglindan)

**Comment by Stew-rt** [comment]
I've been told if you log in to your foundry account and request the transfer via their contact Us section, they can perform the transfer.

I'll confirm your foundry username in a response to them.

**Comment by DC23** [comment]
Ok, I'll do that.

The GitHub repo transfer has started.

**Comment by DC23** [comment]
I've notified Foundry support, so with confirmation from both of us they should be able to action the transfer on their side as well. This makes me really happy. The legacy of your module will continue, and BFRPG players in Foundry will have their content once more :)

**Comment by Stew-rt** [comment]
good, good.
hopefully this new data concept will make maintaining this less of a time sink.

**Comment by DC23** [comment]
That's the plan. Aiming for a data pipeline that can, more or less, take raw text that's cut and paste from the PDFs and process that through to the reference JSON which is published to GitHub. Then the reference JSON is consumed by downstream projects that further transform it for their projects. For this project, that means import macros running inside Foundry that munge the data into the Foundry data objects.

Of course, it's going to be work to build all that, but the vision is to reduce work on updates over the long run compared to hand inputting data.

It doesn't solve the linking of assets like icons though. Probably need to do that by hand, then on updates match entries by name so that part doesn't need redoing. Not sure yet.

**Comment by DC23** [comment]
In the short term, we are going to convert the current data in this repo to the new database formats and release a Foundry v12 edition with BFRPG 3e data as a short-term solution. It's better than nothing.

**Comment by DC23** [comment]
Closing this. The transfer of ownership is complete on both the GitHub and Foundry side. I have the "Foundry v12 with 3e content" release completed and in pre-release testing, and the BFRPG reference data project is underway, with monster/bestiary data completed.
