### ISSUE TITLE
Missing required fields to support import to v10 compatible 'basicfantasyrpg' system.

### ISSUE THREAD

**Issue by totallybanjaxed** [DC23/basicfantasyrpg-corerules-en#5]
Hey there @Stew-rt, I had a quick look at installing this into the recently updated, v10 compatible, 'basicfantasyrpg' system and got some errors:

```
Error: Unable to load valid module manifest data from "https://github.com/Stew-rt/basicfantasyrpg-corerules-en/releases/latest/download/module.json"
Module Model Validation Errors
[Module.packs]: Model Validation Errors
The Compendium pack "spells-magic-user-6th-level" of the "Item" type must declare the "system" upon which it depends.
The Compendium pack "spells-magic-user-5th-level" of the "Item" type must declare the "system" upon which it depends.
.....etc. etc.
```

I can see that it just needs the v10 required fields added in to module.json.

Are you happy to accept PRs?  If I had some time I could perhaps also try and help with the monster additions?  It's a hell of a lot of data entry to get through!  Would just be good to get a list of what's still missing.

Cheers,
Ian

**Comment by Stew-rt** [comment]
Thanks totallybanjaxed

Not sure when i'm going to find time to correct this, other commitments have stopped me working on this as-it-is.. PRs are more than welcome, though! :)

If you wanted to work on the data entry part - i was working through the sections in the monsters section of the core rules book.
If you look at the commit log on the monsters branch, you will see how far i got from the commit messages....

**Comment by totallybanjaxed** [comment]
Great, yeah I'll have a look at the commit messages then and try and see where you got to.  I'll look a little more into the v10 module fields as there are a few things in there that have changed from when I last played with any compendium stuff.  If I can get it working then I'll look to add more data and see if we can knock out a version of it.  :)

**Comment by totallybanjaxed** [comment]
Will close this off now that it is setup for v10.
